### ISSUE TITLE
IRCv3

### ISSUE THREAD

**Issue by travankor** [nutjob-laboratories/erk#1]
Just wondering, do you plan to add [IRCv3](https://ircv3.net/) features to your client? I'm not interested in all the new features, but would personally like more [authentication options](https://ircv3.net/docs/sasl-mechs), like SASL EXTERNAL.

**Comment by danhetrick** [comment]
There's no plan for it at the moment. Right now, I'm focusing on getting the main client to work cross-platform (Windows and Linux work, I'm working on OSX now). Once the client is functioning properly, I'll look into it.
