### ISSUE TITLE
[Suggestion] Custom leave/dnd/quit messages.

### ISSUE THREAD

**Issue by 0xAB51NTH** [nutjob-laboratories/erk#3]
Hi, i have small suggestion would it be possible to have custom leave/dnd/quit messages that will be saved soo i dont have to type  _/quit my funny quit text here_ ? I dont think it is something really hard to create.

**Comment by 0xAB51NTH** [comment]
oh it seems like theme generation tool have not done good enough job, is there a way to turn darkmode like on linux screenshot in repo?

**Comment by danhetrick** [comment]
Custom quit messages: that's a pretty good idea :-) I'll work on that once I get a bit more done on the scripting engine.
Custom themes: in Erk, they're called "styles". You can edit the style for any chat by right clicking on the chat window, and select "Edit style" from the "Style" menu in the context menu. If you want to edit *all* window styles (what you want *every* window to look like when you enter a chat), select "Style editor" from the "Settings" menu, and save your changes. The dark form widgets (like the background of the window, etc) can be changed with the settings your OS comes with. I used a dark theme available in Linux Mint, running Cinnamon.

**Comment by danhetrick** [comment]
Custom quit/part message is now in the code. Set the custom quit/part message in the "Preferences" dialog.
